/**
 * Creates an Amazon search link only after the owner supplies an approved Associates tracking ID.
 * Product cards deliberately do not call this function during launch, because no verified tag or
 * current product data is available yet.
 */
export function buildAmazonSearchLink(productQuery: string, trackingId?: string) {
  const cleanQuery = productQuery.trim();
  const cleanTag = trackingId?.trim();

  if (!cleanQuery || !cleanTag || !/^[A-Za-z0-9-]{3,64}$/.test(cleanTag)) return null;

  const params = new URLSearchParams({ k: cleanQuery, tag: cleanTag });
  return `https://www.amazon.com/s?${params.toString()}`;
}

export const affiliateActivationChecklist = [
  "Publish the original guides on the live Gear Guru Guide domain and identify that domain and the connected social channels in the Associates application.",
  "Confirm the website is accepted into Amazon Associates and that the approved target marketplace and tracking ID are correct.",
  "Use approved current product data or Creators API content before presenting pricing, ratings, availability, or product images.",
  "Place a clear affiliate disclosure above or immediately adjacent to each monetized recommendation and display the required Amazon Associate statement on the site.",
  "Use a direct Special Link generated by Amazon; do not cloak, auto-redirect, or put Special Links in email, PDFs, or offline promotion.",
] as const;
